name: Deploy to EC2 instance

on:
  workflow_run:
    workflows: ["Build and push"]
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to EC2 instance

    steps:
      - uses: actions/checkout@v3

      - name: Deploy via ssh
        uses: easingthemes/ssh-deploy@v4.0.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: "ec2-54-233-192-136.sa-east-1.compute.amazonaws.com"
          REMOTE_USER: "ubuntu"
          TARGET: "/home/ubuntu/pelandobot"
          SCRIPT_AFTER: |
            echo HOST=${{ secrets.HOST }} > ./pelandobot/.env
            echo API_KEY=${{ secrets.API_KEY }} >> ./pelandobot/.env
            echo ${{ secrets.WEBHOOK_CERT }} | base64 --decode > ./pelandobot/webhook_cert.pem
            echo ${{ secrets.WEBHOOK_PKEY }} | base64 --decode > ./pelandobot/webhook_pkey.pem
